### PR TITLE
Applying change tested by jasoncodes (#180)

### PR DESCRIPTION
**Pull request by sh00t2kill**
* Applying change tested by jasoncodes

* Removed new lines at the end of README

---------

### CODE REVIEW

**Review by elad-bar — APPROVED** [review]
changing the code should be done in a branch then PR to developer then to main,
code is ok

**Review by elad-bar — CHANGES_REQUESTED** [review]
pls add manifest version update to 11 and readme documentation

**Comment by sh00t2kill** [comment]
"changing the code should be done in a branch then PR to developer then to main,"

This is what happened. This is the PR to main. Theres probably not a whole lot of point releasing this at the moment anyway with all the async issues that need to be fixed. 

I havent had the time to look unfortunately.

**Comment by elad-bar** [comment]
Sorry, missed it, can you pls just update version in manifest and changelog?

Thanks

**Review by elad-bar — APPROVED** [review]

**Comment by elad-bar** [comment]
@sh00t2kill merged, if you have time pls release new version, in case you don't i will release it later today

thanks

**Pull request merged**
