### PR TITLE
Applying change tested by jasoncodes

### PR DESCRIPTION
**Pull request by sh00t2kill**
Address issue 178, where the broker disconnects and doesnt reconnect

### CODE REVIEW

**Comment by elad-bar** [comment]
It means that when session is terminated you are not unsubscribing topic, so once it will get reconnect it will subscribed and there will be 2 listeners for the same topic, actions will be performed 2 times meaning more cpu and memory,
Once it will disconnect and reconnect agains 3 times per topic and so on...

**Comment by elad-bar** [comment]
checked it once again, the fix will unsubscribed when the component will terminate only, it happens only after restart, so don't know how it solved the problem, there are 2 potential fix for it:
1. remove unsubscribing and set the client as clean session = Fasle (prefered, checking it now)
2. move unsubscrbing upon disconnection and not on terminate, so every disconnection it will unsubscribe and subscribe topics

as written above, testing option 1 which should be most efficiant, will report back

**Comment by elad-bar** [comment]
that pull request was applied directly to develop branch, it doesn't matter if i will approve it or not

**Comment by sh00t2kill** [comment]
I know.
I tagged you for approval because I know you were looking into it.

Since applying this change, I hae seen the broker disconnect and automatically reconnect again, without any interaction from HA or having to restart either the integration or HA itself.

**Pull request merged**
